{{- if and .Values.pdb -}}
{{- $fullName := include "fellowship.fullname" . -}}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "fellowship.chart" . }}
    release: {{ .Release.Name }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
{{- end }}
