apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "fellowship.chart" . }}
    release: {{ .Values.image.tag }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.Service.type }}
  ports:
{{- range $i, $port := .Values.Ports }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
    protocol: TCP
    targetPort: {{ $port.targetPort }}
{{- end }}
  selector:
  {{- if .Values.canary }}
    app: {{ .Release.Name }}-primary
  {{- else }}
    app: {{ .Release.Name }}
  {{ end }}                                                                                               
